name: Build touchHLE

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-TouchHLE:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # touchHLE's git-describe versioning needs tag history
    - name: Get Submodules
      run: git submodule update --init

    - name: Install Dependencies
      run: brew install boost mingw-w64

    - name: Try to get cached copy of Boost
      id: cache-boost
      uses: actions/cache@v3
      with:
        path: vendor\boost
        key: boost_1_81_0
    - if: ${{ steps.cache-boost.outputs.cache-hit != 'true' }}
      name: Download Boost
      run: curl -L -o boost_1_81_0.7z "https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0.7z"
    - if: ${{ steps.cache-boost.outputs.cache-hit != 'true' }}
      name: Extract Boost
      run: 7z -ovendor x boost_1_81_0.7z && mv ./vendor/boost_1_81_0 ./vendor/boost

    - name: Fetch Toolchains
      run: rustup target add x86_64-unknown-linux-gnu && rustup target add x86_64-pc-windows-gnu

    - name: Build MacOS
      run: cargo build --release && mv target/release/touchHLE .
    - uses: actions/upload-artifact@v3
      with:
        name: touchHLE_macOS_x86_64
        path: touchHLE

    - name: Build Windows
      run: rm ./touchHLE && cargo build --release --target x86_64-pc-windows-gnu && mv target/releasex86_64-linux-gnu/touchHLE .
    - uses: actions/upload-artifact@v3
      with:
        name: touchHLE_Windows_x86_64
        path: touchHLE.exe
        
    - name: Build Linux
      run: rm ./touchHLE && cargo build --release --target x86_64-unknown-linux-gnu --no-default-features && mv target/releasex86_64-linux-gnu/touchHLE .
    - uses: actions/upload-artifact@v3
      with:
        name: touchHLE_linux_x86_64
        path: touchHLE
